#include <iostream>

int main() {

	try {


	}
	catch (int exception) {

		std::cout << exception;
	}
}